Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/jupyter_core/utils/__init__.py", line 154, in wrapped
    asyncio.get_running_loop()
RuntimeError: no running event loop

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/nbclient/client.py", line 1319, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/jupyter_core/utils/__init__.py", line 158, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
datos=np.genfromtxt("WDBC.dat",  delimiter=",")
#print(datos[0:4,:])
------------------


[31m---------------------------------------------------------------------------[39m
[31mFileNotFoundError[39m                         Traceback (most recent call last)
[36mCell[39m[36m [39m[32mIn[2][39m[32m, line 1[39m
[32m----> [39m[32m1[39m datos=[43mnp[49m[43m.[49m[43mgenfromtxt[49m[43m([49m[33;43m"[39;49m[33;43mWDBC.dat[39;49m[33;43m"[39;49m[43m,[49m[43m  [49m[43mdelimiter[49m[43m=[49m[33;43m"[39;49m[33;43m,[39;49m[33;43m"[39;49m[43m)[49m
[32m      2[39m [38;5;66;03m#print(datos[0:4,:])[39;00m

[36mFile [39m[32m/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/numpy/lib/_npyio_impl.py:2007[39m, in [36mgenfromtxt[39m[34m(fname, dtype, comments, delimiter, skip_header, skip_footer, converters, missing_values, filling_values, usecols, names, excludelist, deletechars, replace_space, autostrip, case_sensitive, defaultfmt, unpack, usemask, loose, invalid_raise, max_rows, encoding, ndmin, like)[39m
[32m   2005[39m     fname = os.fspath(fname)
[32m   2006[39m [38;5;28;01mif[39;00m [38;5;28misinstance[39m(fname, [38;5;28mstr[39m):
[32m-> [39m[32m2007[39m     fid = [43mnp[49m[43m.[49m[43mlib[49m[43m.[49m[43m_datasource[49m[43m.[49m[43mopen[49m[43m([49m[43mfname[49m[43m,[49m[43m [49m[33;43m'[39;49m[33;43mrt[39;49m[33;43m'[39;49m[43m,[49m[43m [49m[43mencoding[49m[43m=[49m[43mencoding[49m[43m)[49m
[32m   2008[39m     fid_ctx = contextlib.closing(fid)
[32m   2009[39m [38;5;28;01melse[39;00m:

[36mFile [39m[32m/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/numpy/lib/_datasource.py:192[39m, in [36mopen[39m[34m(path, mode, destpath, encoding, newline)[39m
[32m    155[39m [38;5;250m[39m[33;03m"""[39;00m
[32m    156[39m [33;03mOpen `path` with `mode` and return the file object.[39;00m
[32m    157[39m 
[32m   (...)[39m[32m    188[39m 
[32m    189[39m [33;03m"""[39;00m
[32m    191[39m ds = DataSource(destpath)
[32m--> [39m[32m192[39m [38;5;28;01mreturn[39;00m [43mds[49m[43m.[49m[43mopen[49m[43m([49m[43mpath[49m[43m,[49m[43m [49m[43mmode[49m[43m,[49m[43m [49m[43mencoding[49m[43m=[49m[43mencoding[49m[43m,[49m[43m [49m[43mnewline[49m[43m=[49m[43mnewline[49m[43m)[49m

[36mFile [39m[32m/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/numpy/lib/_datasource.py:529[39m, in [36mDataSource.open[39m[34m(self, path, mode, encoding, newline)[39m
[32m    526[39m     [38;5;28;01mreturn[39;00m _file_openers[ext](found, mode=mode,
[32m    527[39m                               encoding=encoding, newline=newline)
[32m    528[39m [38;5;28;01melse[39;00m:
[32m--> [39m[32m529[39m     [38;5;28;01mraise[39;00m [38;5;167;01mFileNotFoundError[39;00m([33mf[39m[33m"[39m[38;5;132;01m{[39;00mpath[38;5;132;01m}[39;00m[33m not found.[39m[33m"[39m)

[31mFileNotFoundError[39m: WDBC.dat not found.

